---
title: "Dataset Creation"
author: "Joy Zhang"
date: "2023-11-19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("C:/Users/Joy Zhang/OneDrive/Desktop/UMICH/BIOSTAT 625")

library(readxl)
library(dplyr)
library(ggplot2)
library(tableone)

# read in data
# diabetes_data <- read.csv("diabetes_data.csv")

# factor covariates
diabetes_data$Diabetes_binary <- factor(diabetes_data$Diabetes_binary)
levels(diabetes_data$Diabetes_binary) <- c("No Diabetes", "Diabetes or Pre-Diabetic")
diabetes_data$HighBP <- factor(diabetes_data$HighBP)
diabetes_data$HighChol <- factor(diabetes_data$HighChol)
diabetes_data$Smoker <- factor(diabetes_data$Smoker)
diabetes_data$Stroke <- factor(diabetes_data$Stroke)
diabetes_data$HeartDiseaseorAttack <- factor(diabetes_data$HeartDiseaseorAttack)
diabetes_data$PhysActivity <- factor(diabetes_data$PhysActivity)
diabetes_data$Fruits <- factor(diabetes_data$Fruits)
diabetes_data$Veggies <- factor(diabetes_data$Veggies)
diabetes_data$HvyAlcoholConsump <- factor(diabetes_data$HvyAlcoholConsump)
diabetes_data$AnyHealthcare <- factor(diabetes_data$AnyHealthcare)
diabetes_data$NoDocbcCost <- factor(diabetes_data$NoDocbcCost)
diabetes_data$GenHlth <- factor(diabetes_data$GenHlth)
diabetes_data$DiffWalk <- factor(diabetes_data$DiffWalk)
diabetes_data$Sex <- factor(diabetes_data$Sex)
```

Re-categorize age
```{r}
# categorize age into 4 groups
# 18 < age < 35: 1, 2, 3
# 35 < age < 50: 4, 5, 6
# 50 < age < 65: 7, 8, 9
# age > 65: 10, 11, 12, 13

diabetes_data$age_cat <- cut(diabetes_data$Age, 
                   breaks=c(1, 4, 7, 10, 13),
                   include.lowest=TRUE,
                   right=FALSE,
                   labels = c(0, 1, 2, 3))
levels(diabetes_data$age_cat) <- c("Under 35", "35-49", "50-65", "Over 65")
```

Re-categorize income
```{r}
# categorize income into 3 groups
# income < 25000 ---> low: 1, 2, 3, 4
# 25000 < income < 75000 ---> medium: 5, 6, 7
# income > 75000 ---> high: 8

diabetes_data$income_cat <- cut(diabetes_data$Income, 
                                breaks = c(1, 5, 7, 8),
                                include.lowest = TRUE,
                                right = FALSE,
                                labels = c(0, 1, 2))
levels(diabetes_data$income_cat) <- c("Low Income", "Medium Income", "High Income")
```

Re-categorize education
```{r}
# categorize education into 2 groups
# never attended college: 1, 2, 3, 4
# attended college: 5, 6

diabetes_data$edu_cat <- cut(diabetes_data$Education, 
                   breaks=c(1, 5, 6),
                   include.lowest=TRUE,
                   right=FALSE,
                   labels = c(0, 1))
levels(diabetes_data$edu_cat) <- c("No College", "College")
```

Re-categorize physical health
```{r}
# categorize physical health into 2 groups
# physical illness or injury days in past 30 days < 5
# physical illness or injury days in past 30 days >= 5

diabetes_data$PhysHlth_cat <- cut(diabetes_data$PhysHlth, 
                        breaks=c(0, 5, 30),
                        include.lowest=TRUE,
                        right=FALSE,
                        labels = c(0, 1))
levels(diabetes_data$PhysHlth_cat) <- c("Low Physical Health", "High Physical Health")
```

Re-categorize mental health
```{r}
# categorize mental health into 2 groups
# mental illness days in past 30 days < 5
# mental illness days in past 30 days >= 5

diabetes_data$MentHlth_cat <- cut(diabetes_data$MentHlth, 
                        breaks=c(0, 5, 30),
                        include.lowest=TRUE,
                        right=FALSE,
                        labels = c(0, 1))
levels(diabetes_data$MentHlth_cat) <- c("Low Mental Health", "High Mental Health")
```

Upload data as csv
```{r}
write.csv(diabetes_data, "diabetes_data.csv")
```



